# * ARCHIVO: wrangler.toml
# * ARQUITECTURA: Configuración de Infraestructura (Cloudflare Pages)
# * * PROPÓSITO ESTRATÉGICO:
# * Definir el entorno de ejecución, las variables de compatibilidad y los enlaces 
# * a recursos externos (D1) para que el proyecto funcione en la infraestructura de Cloudflare.
# * * RESPONSABILIDADES:
# * 1. Identificación: Nombrar el proyecto dentro de la cuenta de Cloudflare.
# * 2. Motor de Ejecución: Establecer la fecha de compatibilidad y banderas de Node.js.
# * 3. Orquestación de Base de Datos: Vincular la base de datos D1 "zoe-plasma-db" al código.
# * 4. Rutas de Salida: Definir dónde se encuentran los archivos estáticos generados.

name = "zoeplasmabeauty"
compatibility_date = "2026-02-24"
compatibility_flags = ["nodejs_compat"]

# NOTA TÉCNICA: Esta carpeta es generada por el comando 'next-on-pages' durante el build.
# En desarrollo local, si esta carpeta está vacía, Wrangler puede devolver un error 404.
# pages_build_output_dir = ".vercel/output/static"

# ENLACE DE BASE DE DATOS (Binding)
# Le decimos a Cloudflare que cuando el código llame a la variable "DB",
# debe conectarse a esta base de datos específica.
[[d1_databases]]
binding = "DB" # Simplificamos el nombre a "DB" para facilitar su uso en el código
database_name = "zoe-plasma-db"
database_id = "2222ba6c-1921-4fc8-812f-282918e130e4"
migrations_dir = "drizzle"